Tnw
MahmoudBakr23/Responsive-Web-Design pull request #2
Opened 2020-06-21 14:23 UTC by MahmoudBakr23

The Next Web Website Clone.
Done with HTML, CSS.

2020-06-21 16:23 UTC, sumancrest0001 commented
**Status: changes required :gear: 
Impressive work TEAM.**
You have created a perfect clone of the original page. Layout and responsiveness are very good. But there are a couple of improvements to be made to get approved. I am confident that it will not take that long to change. Please make the following changes.
**[NOTE] optional changes are not mandatory but nice to have.**

[Required] Remove the vertical lines on left and right side of the hamburger menu.
![Screenshot from 2020-06-21 21-50-15](https://user-images.githubusercontent.com/37747619/85229655-c5d58980-b40a-11ea-8dd0-759c0903f4e9.png)

[Required] Let's use the same colors as on the original page for the footer backgrounds and texts below article titles.
### changes for medium screen
[Required] Let's give more width to the secondary articles.
your layout :point_down: 
![Screenshot from 2020-06-21 22-06-32](https://user-images.githubusercontent.com/37747619/85229788-92472f00-b40b-11ea-9185-402030c3dc58.png)

Original layout :point_down: 
![Screenshot from 2020-06-21 22-06-15](https://user-images.githubusercontent.com/37747619/85229795-9d01c400-b40b-11ea-8c2a-21769d080ad0.png)

2020-06-21 16:26 UTC, sumancrest0001 commented on main.css
> +  background-size: cover;
[Required] Even though the stylings of elements are good. there are a lot of repeated codes that are not necessary. Let's follow the DRY principle and optimize the CSS file. [This article](https://speckyboy.com/good-bad-css-practices/) might be helpful.

2020-06-21 16:27 UTC, sumancrest0001 commented on main.css
> +}
[Required] Even though the stylings of elements are good. there are a lot of repeated codes that are not necessary. Let's follow the DRY principle and optimize the CSS file. [This article](https://speckyboy.com/good-bad-css-practices/) might be helpful.

2020-06-21 16:29 UTC, sumancrest0001 requested changes
**Kindly make the requested changes and fill up another review form.
If you have any questions regarding the review, DM me on slack Suman Shrestha
Happy coding !!!!**

2020-06-21 20:31 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @MahmoudBakr23  and @Abidoyinsola1! 👋👋  
You have done a great job implementing the changes requested by the previous TSE! 👍 You have also done a wonderful job with your project so far! It looks really good! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- [ ] I see that you have removed the vertical lines as was requested by the previous TSE 👍 However, the layout navigation bar on the medium screen now appears to have broken. Please fix this. 👇 
![Screen Shot 2020-06-21 at 10 26 28 PM](https://user-images.githubusercontent.com/48804258/85234551-59f52000-b40e-11ea-8aec-c7305d752981.png)

- [ ] Please see my comments for additional changes. Please use my comments as a guide and search for more instances of repeated CSS rules. 


****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2020-06-21 20:33 UTC, BrittanyBlake commented on main.css
> +}
As requested by the previous TSE, please use the DRY principle to optimize your CSS file

2020-06-21 20:34 UTC, BrittanyBlake commented on main.css
> +  }
As requested by the previous TSE, please use the DRY principle to optimize your CSS file

2020-06-21 20:35 UTC, BrittanyBlake commented on main.css
> +  }
As requested by the previous TSE, please use the DRY principle to optimize your CSS file

2020-06-21 23:35 UTC, peterrobert requested changes
### CHANGES REQUIRED :recycle: :stop_sign: 
**HELLO** @MahmoudBakr23  **VERY IMPRESSIVE WORK SO FAR** :+1: 
You have done such a great job implementing the changes required by the previous TSE :+1: :clap: 

However, there are a few changes that require to be made. KIndly work on the following and submit your project for another review :smile: 

- [ ]  There are still some responsiveness issues in your menu bar Kindly fix this issues.

![menu responsive](https://user-images.githubusercontent.com/32361963/85237574-96397800-b430-11ea-9f88-534997ae3cec.jpg)

- [ ] I have noticed that there are some CSS issues in your styles. You can use this [tool](https://jigsaw.w3.org/css-validator/validator) to double-check your CSS
![css errors](https://user-images.githubusercontent.com/32361963/85237605-cda82480-b430-11ea-840d-0eef75115309.jpg)

kindly submit your project once you fix the issues above :smile: 

If you have any question concerning the review kindly contact me via slack on @peterrobert

### HAPPY CODING :computer:

2020-06-22 01:37 UTC, elmejdki approved these changes
# Wooow, Great job guys :clap: your clone looks amazing :tophat:
### status: approved

you can merge now to master your project was approved.

### Happy Coding. :smiley:

2020-06-22 02:34 UTC, merged